

CREATE TABLE IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (TABLE_NAME)
) ;



CREATE TABLE STCTCCMMNCLCODE (
  CL_CD char(3) NOT NULL,
  CL_CD_NM varchar(60) DEFAULT NULL,
  CL_CD_DC varchar(200) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  FRST_REG_DT datetime DEFAULT NULL,
  FRST_RGTR_ID varchar(20) DEFAULT NULL,
  LAST_CHG_DT datetime DEFAULT NULL,
  LAST_CHG_USR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CL_CD)
) ;



CREATE TABLE STCTCCMMNCODE (
  CD_ID varchar(20) NOT NULL,
  CD_ID_NM varchar(60) DEFAULT NULL,
  CD_ID_DC varchar(200) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  CL_CD char(3) DEFAULT NULL,
  FRST_REG_DT datetime DEFAULT NULL,
  FRST_RGTR_ID varchar(20) DEFAULT NULL,
  LAST_CHG_DT datetime DEFAULT NULL,
  LAST_CHG_USR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CD_ID),
  KEY R_179 (CL_CD),
  CONSTRAINT STCTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CD) REFERENCES STCTCCMMNCLCODE (CL_CD)
) ;



CREATE TABLE STCTCCMMNDETAILCODE (
  CD_ID varchar(20) NOT NULL,
  CD varchar(15) NOT NULL,
  CD_NM varchar(60) DEFAULT NULL,
  CD_DC varchar(200) DEFAULT NULL,
  USE_YN char(1) DEFAULT NULL,
  FRST_REG_DT datetime DEFAULT NULL,
  FRST_RGTR_ID varchar(20) DEFAULT NULL,
  LAST_CHG_DT datetime DEFAULT NULL,
  LAST_CHG_USR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (CD_ID,CODE),
  CONSTRAINT STCTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CD_ID) REFERENCES STCTCCMMNCODE (CD_ID)
) ;

CREATE TABLE STCTNAUTHORGROUPINFO (
  GRP_ID char(20) NOT NULL DEFAULT '',
  GRP_NM varchar(60) NOT NULL,
  GRP_CRT_DT char(20) NOT NULL,
  GRP_DC varchar(100) DEFAULT NULL,
  PRIMARY KEY (GRP_ID)
) ;

CREATE TABLE TN_USR_INFO (
  USR_ID VARCHAR(16) NOT NULL COMMENT '사용자ID',
  LGN_ACNT_ID VARCHAR(30) COMMENT '로컬로그인계정ID',
  LGN_ACNT_PSWD VARCHAR(40) COMMENT '로컬로그인계정비밀번호',
  SNS_ID VARCHAR(50) COMMENT '소셜로그인ID',
  SNS_TYPE_CD VARCHAR(10) COMMENT '소셜로그인타입코드',
  SNS_CNCT_DT DATE COMMENT '소셜로그인연동일시',
  NICK_NM VARCHAR(20) NOT NULL COMMENT '닉네임',
  USR_EML VARCHAR(254) COMMENT '이메일',
  USR_BRDT VARCHAR(20) NOT NULL COMMENT '생년월일',
  SXDS_CD CHAR(1) NOT NULL COMMENT '성별코드',
  MBL_TELNO VARCHAR(20) COMMENT '휴대전화번호',
  GRP_ID CHAR(20) NOT NULL COMMENT '권한그룹ID',
  JOIN_DT DATE COMMENT '가입일시',
  MDFCN_DT DATE COMMENT '수정일시',
  WHDWL_DT DATE COMMENT '탈퇴일시',
  PRIMARY KEY (USR_ID)
) COMMENT='사용자정보';


CREATE TABLE TH_TRND_INQ_HST (
  HST_ID VARCHAR(16) NOT NULL COMMENT '이력ID',
  USR_ID VARCHAR(16) NOT NULL COMMENT '사용자ID',
  SRCH_KWRD_CN VARCHAR(20) COMMENT '검색키워드',
  GDS_CLSF_ONE_NM VARCHAR(20) COMMENT '상품첫번째분류',
  GDS_CLSF_TWO_NM VARCHAR(20) COMMENT '상품두번째분류',
  GDS_CLSF_THR_NM VARCHAR(20) COMMENT '상품세번째분류',
  GDS_CLSF_FOR_NM VARCHAR(20) COMMENT '상품네번째분류',
  SRCH_DT DATE COMMENT '검색일시',
  INQ_PRD_UNIT_CD VARCHAR(5) COMMENT '조회기간구간단위',
  INQ_PRD_BGNG_YMD VARCHAR(8) COMMENT '조회기간시작일',
  INQ_PRD_END_YMD VARCHAR(8) COMMENT '조회기간종료일',
  DEVICE_TYPE_CD VARCHAR(5) COMMENT '기기종류',
  SXDS_CD CHAR(1) COMMENT '성별코드',
  AGE_CD CHAR(3) COMMENT '연령코드',
  PRIMARY KEY (HST_ID)
) COMMENT='트렌드조회이력';


CREATE TABLE TH_GDS_INQ_HST (
  GDS_HST_ID VARCHAR(16) NOT NULL COMMENT '상품조회이력ID',
  USR_ID VARCHAR(16) NOT NULL COMMENT '사용자ID',
  INQ_GDS_NM VARCHAR(50) NOT NULL COMMENT '조회상품명',
  GDS_CLSF_ONE_NM VARCHAR(20) COMMENT '상품첫번째분류',
  GDS_CLSF_TWO_NM VARCHAR(20) COMMENT '상품두번째분류',
  GDS_CLSF_THR_NM VARCHAR(20) COMMENT '상품세번째분류',
  GDS_CLSF_FOR_NM VARCHAR(20) COMMENT '상품네번째분류',
  GDS_INQ_DT DATE COMMENT '상품조회일시',
  PRIMARY KEY (GDS_HST_ID)
) COMMENT='상품조회이력';


CREATE TABLE TN_RPT_MNG (
  RPT_ID VARCHAR(16) NOT NULL COMMENT '보고서ID',
  RPT_CRT_DT DATE COMMENT '생성일시',
  RPT_CN VARCHAR(1000) COMMENT '보고서내용',
  RPT_SPRTN_CD VARCHAR(3) NOT NULL COMMENT '보고서구분코드',
  PRIMARY KEY (RPT_ID)
) COMMENT='보고서관리';


CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GRP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM STCTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GRP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM STCTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM STCTNENTRPRSMBER 
;